# === Stage 73: Add a lightweight HTML report export ===
# Project: AssetDesk
def export_html_report(items, custodians):
    """Export asset report as a self-contained HTML string."""
    lines = ["<html><head><style>"]
    lines.append("body { font-family: sans-serif; margin: 20px; }")
    lines.append("h1 { color: #333; border-bottom: 2px solid #667eea; padding-bottom: 8px; }")
    lines.append("table { border-collapse: collapse; width: 100%; margin-top: 16px; }")
    lines.append("th, td { border: 1px solid #ddd; padding: 8px 12px; text-align: left; }")
    lines.append("th { background-color: #667eea; color: white; }")
    lines.append("tr:nth-child(even) { background-color: #f9f9ff; }")
    lines.append("tr:hover { background-color: #eef0ff; }")
    lines.append("footer { margin-top: 30px; font-size: 12px; color: #888; border-top: 1px solid #eee; padding-top: 10px; }")
    lines.append("</style></head><body>")
    lines.append(f"<h1>AssetDesk Report - {len(items)} items</h1>")

    if custodians and isinstance(custodians, dict):
        cust_map = custodians.get("custodians", [])
        for item in sorted(items, key=lambda x: (x["checkout_date"], x["due_date"])):
            cid = next((c["id"] for c in cust_map if c["id"] == item["custodian_id"]), "Unknown")
            lines.append(f"<p><strong>{item['title']}</strong> - Assigned to {cid} | Due: {item['due_date']} | Status: {'Overdue' if item['status'] == 'overdue' else item['status']}</p>")
    return "<footer>Generated by AssetDesk export</footer></body></html>"
